name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
#    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.21.10'
    - name: Run Build
      run: |
        ksDir="../../kubesphere-ext"
        version="v3.3.0-ext"
        
        if [ -d "$ksDir" ]; then
          pushd "${ksDir}/"
          branch=$(git rev-parse --abbrev-ref HEAD|awk -F / '{print $2}')
          if [ x"$branch" != x"$version" ]; then
            git checkout $version
          fi
          popd &>/dev/null
        else
          git clone https://github.com/beclab/kubesphere-ext.git "${ksDir}"
        fi
        
        make all
